### ISSUE TITLE
What link?

### ISSUE THREAD

**Issue by thoran** [questbeat/anchor#52]
According to the README: "After installing, open Chrome extension settings and setup keyboard shortcut from the bottom right link." I don't see any link at the bottom right. Also, it would be good if those instructions were given in the description on the Chrome Web Store.

**Comment by nek023** [comment]
Sorry, I've just fixed the explanation in d8be09fcc280a49b02faf4531e9242912d7cf6d5.
The description in Chrome Web Store is also being fixed and applied soon.
